thisdir = tools/genxs
SUBDIRS = 
include ../../build/rules.make

LOCAL_MCS_FLAGS = -r:System.Xml.dll
PROGRAM = $(topdir)/class/lib/$(PROFILE)/genxs.exe

CLEAN_FILES = *.exe *.mdb

include ../../build/executable.make
