#!/bin/sh -e

# if we're configuring, /usr/share/doc/mono-mint is a directory,
# and isn't a symlink, replace it with a symlink to mono-common
if [ "$1" = "configure" -a -d /usr/share/doc/mono-mint -a ! -h /usr/share/doc/mono-mint ]; then
	rmdir /usr/share/doc/mono-mint
	ln -s mono-common /usr/share/doc/mono-mint
fi

update-alternatives --install /usr/bin/cli cli /usr/bin/mint 10 --slave /usr/share/man/man1/cli.1.gz cli.1.gz /usr/share/man/man1/mint.1.gz

#DEBHELPER#
