#!/bin/sh -e

# if we're configuring, /usr/share/doc/mono-jit is a directory,
# and isn't a symlink, replace it with a symlink to mono-common
if test "$1" = "configure" && test -d /usr/share/doc/mono-jit && ! test -h /usr/share/doc/mono-jit ; then
        rmdir /usr/share/doc/mono-jit
        ln -s mono-common /usr/share/doc/mono-jit
fi

update-alternatives --install /usr/bin/cli cli /usr/bin/mono 14 --slave /usr/share/man/man1/cli.1.gz cli.1.gz /usr/share/man/man1/mono.1.gz

#DEBHELPER#
